version: '3.7'

services:
  doh:
    image: doh
    configs:
      # This file holds additional host addresses (equal to /etc/hosts)
      - source: hosts_config
        target: /app/hosts
    ports:
      - "53:53/udp"
      - "53:53/tcp"

configs:
  hosts_config:
    name: hosts_config-DoH-0
    file: ./hosts
