# This configuration file is taken from https://github.com/alecmuffett/dohot/blob/master/dnscrypt-proxy.toml

# listen on port 53, all interfaces

listen_addresses = [ '0.0.0.0:5300' ]

# use the following DoH providers from the 'public-resolvers' list;
# see the URL below for details, add the names here...
# 1/ https://dnscrypt.info/public-servers
# 2/ https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md
# 3/ https://download.dnscrypt.info/resolvers-list/v3/onion-services.md

# UPDATE 2021-02: if you comment-out "server_names" (recommended)
# then you will greatly increase the size of your load-balancing DoH
# pool; however doing so MAY restrict access to `onion-cloudflare`
# because of source ordering issues. I'm looking to fix this somehow.

#server_names = [ 'a-and-a', 'cloudflare', 'dnslify-doh', 'google', 'iij', 'nextdns', 'onion-cloudflare', 'powerdns-doh', 't53' ]
server_names = [ 'ahadns-doh-nl-ipv6', 'ahadns-doh-nl', 'ahadns-doh-pl-ipv6', 'ahadns-doh-pl', 'adguard-dns-doh']
disabled_server_names = []

# we want frequent stats on latency, etc, so we poll/log every hour

cert_refresh_delay = 60

doh_servers = true
ipv4_servers = true
ipv6_servers = true
dnscrypt_servers = true

# imma assume IPv4 only, feel free to tweak this if you are IPv6-capable

block_ipv6 = false

# don't let weird queries & typos leak upstream

#block_unqualified = true
#block_undelegated = true

# the goal of using tor is to not care about server logging, so why limit ourselves?

require_nolog = false

# but we *do* want integrity

require_dnssec = true

# and we *probably* want DoH servers that advertise themselves as unfiltered

require_nofilter = true

#force_tcp = true
#proxy = 'socks5://127.0.0.1:9050'

# how long a dns query will wait for a response, in milliseconds (max recommended)

timeout = 10000

# loadbalancing

lb_strategy = 'p2'

# logging

log_level = 2
use_syslog = true
log_files_max_size = 64
log_files_max_age = 7
log_files_max_backups = 4

# less linkability / more privacy at slight performance impact;
# see the notes in the `example-dnscrypt-proxy.toml`

tls_disable_session_tickets = true
tls_cipher_suite = [52392, 49199]

# this server MUST be able to probe the internet, so we should
# configure our firewall so that it's the only one which can use port
# 53; DNSCrypt-proxy will only use these in limited circumstances...

fallback_resolvers = ['1.1.1.1:53', '8.8.8.8:53']
netprobe_address = '8.8.8.8:53'
netprobe_timeout = 60
ignore_system_dns = true

# let's be explicit about caching...

cache = true
cache_size = 4096
cache_min_ttl = 4800
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

# no i am not configuring this resolver as a local DoH listener,
# to do so requires a TLS certificate and that's a world of pain

cloaking_rules = '/app/hosts'

[query_log]
file = '/var/log/dnscrypt-proxy/query.log'

[nx_log]
file = '/var/log/dnscrypt-proxy/nx.log'

[sources]

  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
